### ISSUE TITLE
Mismatching Pose and Twist Data in /odom Topic

### ISSUE THREAD

**Issue by onurulusoy4** [onurulusoy4/DustBusterAI-Software#2]
### Issue Description
When subscribing to the `/odom` topic, I am noticing a discrepancy between the actual velocity of robot and twist data provided in the Odometry message. The twist velocity data do not seem to match the linear velocities which prevents the correct functioning of nav2.

### Expected Behavior
The actual velocity and twist data should be consistent, meaning that the robot's velocity should match the linear and angular velocities provided in the `/odom` topic.

### Actual Behavior
Robot's actual twist velocity in x axis shown in the y axis in topic /odom

When velocity is 0.5 m/s in x axis topic /odom:
```
header:
  stamp:
    sec: 429
    nanosec: 640000000
  frame_id: odom
child_frame_id: chassis
pose:
  pose:
    position:
      x: 0.5563272135762688
      y: 3.9026456074484352
      z: 0.2097998325360038
    orientation:
      x: 0.026366418906572528
      y: 0.028566497915631133
      z: -0.7342818602117713
      w: -0.6777307112082352
  covariance:
  - 1.0e-05
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0e-05
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1000000000000.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1000000000000.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1000000000000.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.001
twist:
  twist:
    linear:
      x: -4.226563650547993e-05
      y: 0.4997449515427235
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: -5.122724551979685e-06
  covariance:
  - 1.0e-05
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0e-05
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1000000000000.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1000000000000.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1000000000000.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.001
---
```
